FROM amazoncorretto:17-alpine-jdk

# Set the working directory
WORKDIR /app

# Copy the JAR file to the container
COPY ./build/libs/*.jar ./

# Add the profiles
COPY src/main/resources/application-dev.properties /app/config/

# Default to dev profile
ENV SPRING_PROFILES_ACTIVE=dev

# Command to run the application
ENTRYPOINT ["java","-jar","/app/JJimGGongMall-0.0.1-SNAPSHOT.jar"]